---
title: "Filter signals"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Filter signals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(rticulate)
```

```{r}
it01_dlc_path <- system.file("extdata/it01-dlc.tsv", package = "rticulate")
it01_dlc <- read_aaa(it01_dlc_path) |> 
  mutate(
    # Let's create an ID for each displacement trajectory of each knot in each recording
    # We need to include both knot and spline because there is also HM spline and STM spline
    knot_displ_id = as.numeric(as.factor(paste0(`Date Time of recording`, spline, knot)))
  ) |> 
  mutate(
    Y_sm = filter_signal(Y, window_length = 7, apply = 2),
    Y_smb = filter_signal(Y, filter = "butter", cutoff_freq = 10, sampling_freq = 67),
    .by = knot_displ_id
  )
```


```{r}
#| label: fs-mean

it01_dlc |>
  group_by(knot_displ_id) |>
  mutate(
    dt = `Time of sample in annot` - lag(`Time of sample in annot`)
  ) |>
  summarise(
    mean_dt = mean(dt, na.rm = TRUE)
  ) |>
  summarise(
    mean_fs = round(mean(1/mean_dt))
  )
```

Mean sampling frequency of 67 frames per second.

```{r}
it01_dlc |> 
  filter(knot == "8") |> 
  ggplot(aes(`Time of sample in annot`, Y, group = `Date Time of recording`)) +
  geom_line(alpha = 0.2) +
  geom_line(aes(y = Y_sm), colour = "red")
```

```{r}
set.seed(13579)
kdi <- sample(unique(it01_dlc$knot_displ_id), 9)
it01_dlc |> 
  filter(knot_displ_id %in% kdi) |> 
  ggplot(aes(`Time of sample in annot`, Y)) +
  geom_line(alpha = 0.2) +
  geom_point(aes(y = Y_sm), colour = "red") +
  facet_wrap(vars(knot_displ_id), scales = "free")
```



```{r}
id_14 <- it01_dlc |> 
  filter(knot_displ_id == 14)

id_14_y <- id_14$Y_sm
id_14_time <- id_14$`Time of sample in annot`

y_re <- resample_signal(id_14_y, id_14_time, by = 2)
y_re_sm <- filter_signal(y_re$signal_int, window_length = 11, apply = 2)
y_re_sm_vel <- get_velocity(y_re_sm)

plot(y_re$time_int, y_re$signal_int); lines(y_re$time_int, y_re_sm, type = "p", col = "red")
plot(y_re$time_int, y_re_sm_vel); lines(y_re$time_int, abs(y_re_sm_vel), col = "red"); lines(y_re$time_int, get_acceleration(y_re_sm), col = "green")
```



```{r}
it01_up <- it01_dlc |> 
  reframe(
    resample_signal(Y_sm, `Time of sample in annot`, by = 3), .by = c(knot_displ_id, knot)
  ) |> 
  mutate(
    Y_sm_up = filter_signal(signal_int, window_length = 11, apply = 2),
    .by = c(knot_displ_id, knot)
  )

it01_up |> 
  filter(knot == 8) |> 
  ggplot(aes(time_int, signal_int)) +
  geom_point(alpha = 0.2) +
  geom_point(aes(y = Y_sm_up), colour = "red", size = 0.25) +
  facet_wrap(vars(knot_displ_id))
```

```{r}
#| warning: false

it01_up |> 
  filter(knot_displ_id == 14) |> 
  mutate(
    Y_sm_up_vel = get_velocity(Y_sm_up)
  ) |> 
  ggplot(aes(time_int, Y_sm_up_vel)) +
  geom_point() +
  geom_line(aes(y = abs(Y_sm_up_vel)), colour = "red") +
  annotate("rect", xmin = 0.3, xmax = 0.55, ymin = -Inf, ymax = Inf, alpha = 0.3)
```

```{r}
y_re_sm_vel_peaks <- pracma::findpeaks(abs(y_re_sm_vel))

plot(y_re$time_int, abs(y_re_sm_vel)); lines(y_re$time_int[y_re_sm_vel_peaks[,2]], y_re_sm_vel_peaks[,1], col = "red", type = "p", pch = 3); lines(y_re$time_int[y_re_sm_vel_peaks[,3]], y_re_sm_vel_peaks[,1], col = "green", type = "p", pch = 18); lines(y_re$time_int[y_re_sm_vel_peaks[,4]], y_re_sm_vel_peaks[,1], col = "blue", type = "p", pch = 18)
```

```{r}
it01_up_win <- it01_up |> filter(knot_displ_id == 14, time_int > 0.3, time_int < 0.55)

it01_up_win_land <- get_landmarks(it01_up_win$Y_sm_up, it01_up_win$time_int)
it01_up_win_land_long <- it01_up_win_land |> 
  pivot_longer(everything(), names_to = "land")

it01_up_win |> 
  ggplot(aes(time_int, abs(get_velocity(Y_sm_up)))) +
  geom_point() +
  geom_vline(data = it01_up_win_land_long |> filter(str_detect(land, "_ons|_off")), aes(xintercept = value))

it01_up_win |> 
  ggplot(aes(time_int, Y_sm_up)) +
  geom_point() +
  geom_vline(data = it01_up_win_land_long |> filter(str_detect(land, "_ons|_off")), aes(xintercept = value)) +
  annotate("rect", ymin = -Inf, ymax = Inf, xmin = it01_up_win_land$peak_1_time + (it01_up_win_land$PLAT_ons - it01_up_win_land$peak_1_time) / 2, xmax = it01_up_win_land$PLAT_off + (it01_up_win_land$peak_2_time - it01_up_win_land$PLAT_off) / 2, fill = "red", alpha = 0.2) +
  labs(
    caption = "The red areas marks the closure onset and offset which are\nthe mid-point between the peak closing velocity and the plateau onset,\nand the mid-point between the plateau offset and the peak opening velocity"
  )
```

