---
title: "Import and plot spline data from AAA"
author: "Stefano Coretta"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, include=FALSE}
library(tidyverse)
theme_set(theme_bw())
library(rticulate)
```

The package `rticulate` facilitates UTI data import and plotting with spline data exported from Articulate Assistant Advanced (AAA). To use the package, load it as usual.

```{r load, eval=FALSE}
library(rticulate)
```

# Import spline data

```{r columns}
columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
)
```


```{r read-aaa}
tongue <- read_aaa(system.file("extdata", "sc01-aaa.tsv", package = "rticulate"), columns)
```

# Plot splines

```{r plot-splines}
plot_splines(tongue)
```

```{r filter-plot}
filter(tongue, label == "max_TD") %>%
    plot_splines()
```

```{r plot-palate}
filter(tongue, label == "max_TD") %>%
    plot_splines(palate = palate) + aes(group = rec.date)
```

